name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
- test

resources:
- repo: self

variables:
  buildConfiguration: 'Release'
  buildVersion: '$(Build.BuildNumber)'
  projects: '**/*.csproj'
  testProjects: '**/*.UnitTest.csproj'

stages:
- stage: Build_Test
  displayName: Build and test

  jobs:
  - job: Build_Test
    displayName: Build and test
    timeoutInMinutes: 300
    pool:
     vmImage: 'windows-latest'
     demands:
      - msbuild
      - visualstudio

    steps:
    - checkout: self
      clean: true

    - task: NuGetToolInstaller@1
      displayName: Install NuGet

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '$(projects)'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '$(projects)'
        arguments: >
          --configuration $(buildConfiguration)
          --no-restore
          /p:Version=$(buildVersion)
          /p:AssemblyVersion=$(buildVersion)
          /p:FileVersion=$(buildVersion)
          /p:InformationalVersion=$(buildVersion)

    - powershell: |
        if (Get-ChildItem -Recurse -Filter *.UnitTest.csproj -File) {
          Write-Host "##vso[task.setVariable variable=RunUnitTests]True"
        }
        else {
          Write-Host "##vso[task.setVariable variable=RunUnitTests]False"
        }
      displayName: Discover unit tests

    - task: DotNetCoreCLI@2
      condition: and(succeeded(), eq(variables['RunUnitTests'], 'True'))
      displayName: Run unit tests
      inputs:
        command: test
        projects: '$(testProjects)'
        arguments: >
          --configuration $(buildConfiguration)
          --no-build

    - task: DotNetCoreCLI@2
      displayName: Pack NuGet packages
      inputs:
        command: pack
        packagesToPack: '$(projects)'
        nobuild: true
        versioningScheme: byEnvVar
        versionEnvVar: buildVersion
        arguments: >
          --configuration $(buildConfiguration)
          --output $(Build.ArtifactStagingDirectory)

    - publish: $(Build.ArtifactStagingDirectory)
      displayName: Publish artifacts
      artifact: SamplesArtifacts

- stage: Deploy
  displayName: Deploy
  dependsOn: Build_Test
  condition: succeeded()

  jobs:
  - job: Deploy
    displayName: Push NuGet packages
    pool:
      name: Default

    steps:
    - checkout: none

    - download: current
      artifact: SamplesArtifacts

    - task: NuGetToolInstaller@1
      displayName: Install NuGet

    - task: NuGetCommand@2
      displayName: Push packages to NuGet.org
      inputs:
        command: push
        packagesToPush: '$(Agent.BuildDirectory)/SamplesArtifacts/**/*.nupkg'